DROP TABLE IF EXISTS sttgaz.stage_crm_requests;
CREATE TABLE sttgaz.stage_crm_requests (
    "skorost"   TIME,
    "region"    VARCHAR(500),
    "holding"   VARCHAR(500),
    "nomer obrashenia"  INT,
    "kod dc"    INT,
    "dealer"    VARCHAR(500),
    "data sozdania" TIMESTAMP,
    "data smeni statusa" TIMESTAMP,
    "status"    VARCHAR(100),
    "comments"  VARCHAR(500),
    "prichina"  VARCHAR(500),
    "istochnic trafica" VARCHAR(100),
    "tip zaiavki"   VARCHAR(100),
    "domen" VARCHAR(500),
    "ip-adres clienta"  VARCHAR(500),
    "nomer RL"  INT,
    "model interesuiushego TS" VARCHAR(500),
    "client id" VARCHAR(500),
    "client"    VARCHAR(500),
    "phone" VARCHAR(500),
    "email" VARCHAR(500),
    "text obrashenia"   VARCHAR(500),
    "soglasie na obrabotcu PD"  VARCHAR(500),
    "soglasie na poluchenie informacii" VARCHAR(500),
    "id"    VARCHAR(500),
    "obrashenie zakrito"    VARCHAR(500),
    "tegi clienta"  VARCHAR(500),
    "status RL" VARCHAR(500),
    "etap prodaz"   VARCHAR(500),
    "oblast clienta"    VARCHAR(500),
    "obshee vremia zvonca"  VARCHAR(500),
    "status sviazannogo sobitiya"   VARCHAR(500),
    "type ocherednogo sobitiya" VARCHAR(500),
    "data ocherednogo sobitiya" VARCHAR(500),
    "otvetstvenniy za RL"   VARCHAR(500),
    "period"	DATE
)
PARTITION BY period;

